require: rubocop-performance

AllCops:
  Include:
    - '**/*.rb'
  Exclude:
    - '*.gemspec'
    - '**/*.builder'
    - '**/*.jbuilder'
    - Rakefile
    - spec/spec_helper.rb
  TargetRubyVersion: '2.3'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'lib/vnstat-ruby.rb'
