AllCops:
  Include:
    - '**/*.rb'
  Exclude:
    - '*.gemspec'
    - '**/*.builder'
    - '**/*.jbuilder'
    - Rakefile
    - spec/spec_helper.rb

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FileName:
  Exclude:
    - Gemfile
